# Generated by Django 2.0 on 2018-05-19 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0002_auto_20180516_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusCobertura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_cobertura', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Início')),
            ],
            options={
                'verbose_name': 'StatusCobertura',
            },
        ),
        migrations.RemoveField(
            model_name='cobertura',
            name='id_cabra',
        ),
        migrations.AlterField(
            model_name='animal',
            name='raca_animal',
            field=models.CharField(choices=[('saanen', 'Saanen'), ('anglo-nubiana', 'Anglo-Nubiana'), ('srd', 'Sem Raça Definida (SRD)')], max_length=50, verbose_name='Raça'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sangue_animal',
            field=models.CharField(blank=True, choices=[('po', 'Puro de Origem'), ('pc', 'Puro de Cruza'), ('1/2', '1/2 Sangue'), ('3/4', '3/4 Sangue'), ('7/8', '7/8 Sangue'), ('15/16', '15/16 Sangue'), ('31/32', '31/32 Sangue')], max_length=50, verbose_name='Sangue'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sexo_animal',
            field=models.CharField(blank=True, choices=[('f', 'Feminino'), ('m', 'Masculino')], max_length=50, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='statuscobertura',
            name='id_cabra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Cabra', to='animais.Animal', verbose_name='Cabra'),
        ),
        migrations.AddField(
            model_name='statuscobertura',
            name='id_cobertura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Cobertura', to='animais.Cobertura', verbose_name='Cobertura'),
        ),
    ]
