# Generated by Django 2.0.4 on 2018-04-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caprino',
            options={'verbose_name': 'Caprino'},
        ),
        migrations.AlterField(
            model_name='caprino',
            name='nome',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='Nome Completo'),
        ),
    ]
